#!/bin/bash

if [ $(whoami) != 'root' ]; then
    echo 'push must be run as root'
    exit -1
fi

#umount /dev/sdb4
duplicity --exclude-other-filesystems --exclude /home/$USER/.cache/duplicity --exclude /proc --no-encryption --progress / $B2_PATH
#mount /dev/sdb4
