#!/bin/bash

duplicity --asynchronous-upload --exclude-other-filesystems --exclude /proc --exclude /tmp --exclude /home/*/.cache/duplicity --exclude /home/soren/Downloads/models/ --exclude /home/soren/Videos/ --progress / file:///mnt/speedyDisk/Backups/
chown -R soren /home/soren/.cache/duplicity/*
chown -R soren /mnt/speedyDisk/Backups/

#toRestore='/home/soren/Desktop/history-1990-01-01.kml' && sudo duplicity restore --progress --file-to-restore $toRestore file:///mnt/speedyDisk/Backups/ $toRestore && sudo chown soren $toRestore
