#!/bin/bash
input=${1:0}

if [ $(whoami) != 'root' ]
then
    ps -ef | egrep -i $input | egrep -i $USER |egrep -iv 'grep' | sed 's/soren *//' | sed 's/root *//' | egrep -iv 'killname' > /tmp/tasks
else
    ps -ef | egrep -i $input |egrep -iv 'grep' | sed 's/soren *//' | sed 's/root *//' | egrep -iv 'killname' > /tmp/tasks
fi

# ps -ef | egrep -i $input | egrep -i $USER |egrep -iv 'grep' | sed 's/soren *//' | sed 's/root *//' | egrep -iv 'killname' > /tmp/tasks

if [ "$(cat /tmp/tasks)" = "" ]; then
  echo "error: task $input not found."
  exit 2
fi

cat /tmp/tasks | sort -nr | sed 's/^[0-9]*  *[0-9]*  *[^ ]*  *[^ ]* [^ ]*  *[^ ]* //ig' | cat -n

read -p "Choose a task by number: " -r

task=$(cat /tmp/tasks | sort -nr | head -n $(echo $REPLY | egrep -o [0-9]*)| tail -1)
taskarg=$(echo $task | sed 's/^[0-9]*  *[0-9]*  *[^ ]*  *[^ ]* [^ ]*  *[^ ]* //ig')
taskpid=$(echo $task | egrep -o '^[0-9]*' | sed 's/^.. //    ')
if [ "$taskpid" = "" ]; then
  echo "error: task $input not found."
  exit 2
fi

read -p "Are you sure you want to kill $taskarg with PID $taskpid? " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
    echo "Killing PID $taskpid..."
    kill -9 $taskpid && echo "Killed"
fi
rm /tmp/tasks
