#!/bin/bash
function checkNetwork() { ping google.com -c 2 -i .2 >/dev/null 2> /dev/null && echo up || echo down; }

while [ "$(checkNetwork)" = "down" ] ;
do
      sleep 2
      echo "network down"
done
echo "network up"
