#!/bin/bash

if [ $(whoami) != 'root' ]; then
    echo 'nvidia-driver-installer must be run as root'
    exit -1
fi
figlet -f slant 'ndi'
#figlet 'ndi'
echo 'by Soren Warner'
echo
echo "If this doesn't work, run add-apt-repository ppa:graphics-drivers/ppa"
echo "Please wait while the system updates..."
apt update --yes > /dev/null 2>/dev/null && apt upgrade --yes > /dev/null 2>/dev/null
echo "Done with updates."

ubuntu-drivers list | sort -nr | cat -n 

read -p "Choose a driver by number: " -r

driver=$(ubuntu-drivers list | sort -nr | head -n $REPLY | tail -1)
echo $driver

read -p "Are you sure you want to install driver $driver? " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
    apt install $driver
    echo "done"
    exit 1
else
    echo "Install aborted"
    exit 2
fi

