#!/bin/bash

if [ $(whoami) != 'root' ]; then
    echo 'nvidia-driver-installer must be run as root'
    exit -1
fi
figlet -f slant 'ndi'
#figlet 'ndi'
echo 'by Soren Warner'
echo
add-apt-repository ppa:graphics-drivers/ppa --yes > /dev/null
echo "fetching updates..."
apt update --yes > /dev/null 2>/dev/null && apt upgrade --yes > /dev/null 2>/dev/null
echo "updates finished"
echo "fetching drivers..."
ubuntu-drivers list > /tmp/drv
echo "finished"

cat /tmp/drv | sort -nr | cat -n 

read -p "Choose a driver by number: " -r

driver=$(cat /tmp/drv | sort -nr | head -n $(echo $REPLY | egrep -o [0-9])| tail -1)

read -p "Are you sure you want to install driver $driver? " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
    apt remove libnvidia* nvidia* --yes -qq
    apt autoremove --yes -qq
    apt install $driver --yes
    apt update --yes -qq
    apt upgrade --yes -qq
    echo "done"
    exit 0
else
    echo "Install aborted"
    exit 2
fi
