#!/bin/bash

#get the current nvidia gpu
gpu=$(sudo lshw -C display | egrep -io '\[geforce [gr]tx? .*\]')
gpu=$(echo $gpu | egrep -io '[a-z0-9 ]*')
echo $gpu

#add header to the list of compatible drivers that we'll be making later. 
echo compatible drivers with $gpu: > usableDrivers

wget https://www.nvidia.com/object/linux-amd64-display-archive.html


#The below section opens the downloaded file, and pulls out JUST the necessary lines for it to work. If you want to try to mess with the regexes, be my guest. 
cat linux-amd64-display-archive.html | egrep -i '<div class="pressItem"><h4><a href="http://www.nvidia.com/Download/driverResults.aspx/' | while read a; do 
#getting the version and URL of the current driver in the list from the archive. 
dVersion=$(echo $a | egrep -io 'version: [0-9]*\.[0-9]*'| sed 's/Version: //ig')
dUrl=$(echo $a | egrep -io 'http:.*en-us')

#downloading the compatibility page for the driver.  
wget http://us.download.nvidia.com/XFree86/Linux-x86_64/$dVersion/README/supportedchips.html -O $dVersion 2> /dev/null
cat $dVersion | egrep '<td>' > tmp

#checking if it's compatible, using the list. 
#  if true, add to the list of compatible drivers.
#  if false, move on. 
if grep -q "$gpu" "tmp"; then
    echo $dVersion $dUrl>> usableDrivers
    echo $dVersion' Y'
else
    echo $dVersion' N'
fi
rm $dVersion

done

# ge
mostRecent=$(sed '2q;d' usableDrivers)
echo $mostRecent
newUrl=$(echo $mostRecent | egrep -io 'http:.*en-us')
echo $newUrl
wget 'http://us.download.nvidia.com/XFree86/Linux-x86_64/'$(echo $mostRecent | egrep -io '^[^ ]*')'/NVIDIA-Linux-x86_64-'$(echo $mostRecent | egrep -io '^[^ ]*')'.run'
rm tmp linux-amd64-display-archive.html
# wget $newUrl -O Recent_page
# confirmUrl=$(cat Recent_page | egrep 'nvEventTracker' | egrep -io 'content/driverdownload.*type=titan"')
# confirmUrl=$(echo https://www.nvidia.com/$confirmUrl)
# echo $confirmUrl
# wget $confirmUrl -O Recent_page
# cat Recent_page | egrep 'nvEventTracker'
