#!/bin/bash

if [ $(whoami) != 'root' ]; then
    echo 'push must be run as root'
    exit -1
fi

#apt autoclean --yes -qq
#apt autoremove --yes -qq
pushBin | egrep -iv "'"
echo

if [ ! -f ~/.bashrc_backup ]
then
    echo 'no backup of /etc/fstab exists! Creating now. '
    cp -v ~/.bashrc ~/.bashrc_backup && echo 'Backup successful'
    chown soren ~/.bashrc_backup
    chown soren ~/.bashrc
fi

if [ $(($(date +"%s") - $(stat -c %Y ~/.bashrc_backup))) -gt 21600 ]
then
    echo '.bashrc_backup older than 6h, making new backup...'
    cp -v ~/.bashrc ~/.bashrc_backup && echo 'Backup successful'
    chown soren ~/.bashrc_backup
    chown soren ~/.bashrc
else
    echo '.bashrc_backup is less than 6h old, no backup made. '
fi
if [ ! -f /etc/fstab_backup ]
then
    echo 'no backup of /etc/fstab exists! Creating now. '
    cp -v /etc/fstab /etc/fstab_backup && echo 'Backup successful'
fi

if [ $(($(date +"%s") - $(stat -c %Y /etc/fstab_backup))) -gt 21600 ]
then
    echo
    echo '/etc/fstab_backup older than 6h, making new backup...'
    cp -v /etc/fstab /etc/fstab_backup && echo 'Backup successful'
else
    echo
    echo '/etc/fstab_backup is less than 6h old, no backup made. '
fi

echo 
cp -v ~/.bashrc ~/.bashrc-backup
chown soren ~/.bashrc-backup
cp ~/.bashrc /root/.bashrc && echo && echo .bashrc pushed to root.
cat /etc/fstab | sed 's/nofail,//g' | sed 's/nofail//g' | sed 's/defaults/defaults,nofail/g' | sed 's/, / /g' > /tmp/fstab.tmp && mv /tmp/fstab.tmp /etc/fstab && echo fstab updated to nofail && echo
apt dist-upgrade --yes
ukuu --clean-cache

apt update --yes
apt upgrade --yes
apt autoclean --yes -qq
apt autoremove --yes -qq
apt clean
