#!/bin/bash
if [ $(whoami) != 'root' ]; then
    echo 'push must be run as root'
    exit -1
fi
apt install --yes -q ${1} > /dev/null 2> /dev/null
${1}
apt purge --yes -q ${1}   > /dev/null 2> /dev/null
#sudo apt autoclean --yes -qq   >/dev/null 2> /dev/null
apt autoremove --yes -qq  > /dev/null 2> /dev/null
